# Generated by Django 5.2.5 on 2025-08-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('in_stock', False), ('stock__gt', 0), _connector='OR'), name='in_stock_requires_positive_stock'),
        ),
    ]
